In [1]:
from urllib.request import urlopen
from bs4 import BeautifulSoup
import pandas as pd


# 교보문고의 베스트셀러 웹페이지를 가져옵니다.

html = urlopen('http://www.kyobobook.co.kr/bestSellerNew/bestseller.laf')
bsObject = BeautifulSoup(html, "html.parser")


# 책의 상세 웹페이지 주소를 추출하여 리스트에 저장합니다.
book_page_urls = []
for cover in bsObject.find_all('div', {'class':'detail'}):
    link = cover.select('a')[0].get('href')
    book_page_urls.append(link)
df = pd.DataFrame(columns=["title", "author", "originalPrice","salePrice"])
# 메타 정보로부터 필요한 정보를 추출합니다.메타 정보에 없는 저자 정보만 따로 가져왔습니다.   
for index, book_page_url in enumerate(book_page_urls):
    html = urlopen(book_page_url)
    bsObject = BeautifulSoup(html, "html.parser")
    title = bsObject.find('meta', {'property':'rb:itemName'}).get('content')
    author = bsObject.select('span.name a')[0].text
    originalPrice = bsObject.find('meta', {'property': 'rb:originalPrice'}).get('content')
    salePrice = bsObject.find('meta', {'property':'rb:salePrice'}).get('content')
    df = df.append(pd.DataFrame({"title":[title], "author":[author], "originalPrice":[originalPrice],"salePrice":[salePrice]}), ignore_index=True)
df

                            title      author originalPrice salePrice
0                    트렌드 코리아 2020         김난도         18000     16200
1                설민석의 한국사 대모험. 12         설민석         12000     10800
2                 지쳤거나 좋아하는 게 없거나         글배우         13500     12150
3                           팩트풀니스      한스 로슬링         19800     17820
4                             에이트         이지성         17000     15300
5                  대한민국 부동산 사용설명서         김학렬         19500     17550
6                    작가들의 비밀스러운 삶       기욤 뮈소         14800     13320
7                       지금 이대로 좋다          법륜         14800     13320
8                         흔한남매. 2   흔한남매 (원작)         11000      9900
9                          부의 인문학       브라운스톤         15000     13500
10                       82년생 김지영         조남주         13000     11700
11  1일 1페이지, 세상에서 가장 짧은 교양 수업 365  데이비드 S. 키더         16000     14400
12                          총 균 쇠   재레드 다이아몬드         28000     25200
13                       90년생이 온다         임홍택         14000     12600
14                             넛지      리처드 탈러         18000     16200
15                    틀 밖에서 놀게 하라         김경희         17800     16020
16           Go Go 카카오프렌즈. 11: 한국         김미영         12000     10800
17                         여행의 이유         김영하         13500     12150
18              너에게만 좋은 사람이 되고 싶어         유귀선         13500     12150
19                           사피엔스      유발 하라리         22000     19800